name: "Planetary Defense Radar"
strategy: "polling"
refresh_interval: 60
polling_url: "https://neo-radar-t4xw3htxya-uc.a.run.app"
polling_verb: "GET"

custom_fields:
  - keyname: author_bio
    field_type: author_bio
    name: "Support & Creator Info"
    description: "Near-earth objects represented by polar coordinates.  Angle represents time with closest being @ 12:00 (NOW).  Distance from center represents distance from Earth."
    email_address: "michaelbgeilich@gmail.com"
    category: discovery,education
